# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72583ad9d90d560bc8b0a2f9346a02ed6bfcd2b766f20297b807f35d8df2c650b3e5dddaaf485fca87ae738703db6d0278e7a4a5771fd256e70ef3c9b90cc5b7

test:
  secret_key_base: 7c6dd8fbfd7e67159540561064bcbde9ad464f4911514e4c40c6863b9564daa939273ea4ad23b08ea8490c1803811ba2b320b6a5ff5dc9834c933812694cccab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
